### ISSUE TITLE
Listă poligoane

### ISSUE THREAD

**Issue by GabrielMajeri** [ToniBiro/Proiect-GeomComp#24]
Deoarece pot să am mai multe poligoane pe ecran, o să am o listă cu toate poligoanele existente. Voi putea selecta un poligon, pentru a-l modifica ulterior.

Lista poate fi generată din JavaScript, și poate fi formată din câteva `<ul>` și `<li>`-uri.

**Comment by Treefold** [comment]
Ar trebui sa existe o lista cu mai multe poligoane care sa poata fi definite si modificate (sau sterse)

**Comment by GabrielMajeri** [comment]
Rezolvat în 369d2898b891fa34e01f0e17075d993417cd39d9
