### ISSUE TITLE
Arhitectură client-server

### ISSUE THREAD

**Issue by GabrielMajeri** [ToniBiro/Proiect-GeomComp#6]
Pentru a modulariza codul și pentru a ne asigura că fiecare componentă are o singură responsabilitate, domnul laborant a sugerat să împărțim aplicația într-un front end și un back end.

Front end-ul se ocupă exclusiv de procesarea datelor de intrare, primește input-ul, și apoi se conectează la back end care rulează algoritmul.

**Comment by Treefold** [comment]
TODO: testare numarul maxim utilizatori
